// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxXbfAmj4S98Ru0-XblorTuKHxzVJvRvs',
    appId: '1:11797163771:web:a7c611eb9e8ee458b6ca5e',
    messagingSenderId: '11797163771',
    projectId: 'guardians-notifications',
    authDomain: 'guardians-notifications.firebaseapp.com',
    storageBucket: 'guardians-notifications.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXFjpqEVI8ELXGyQToYe7aC_ReR-2-5Uo',
    appId: '1:11797163771:android:117614b0b694023fb6ca5e',
    messagingSenderId: '11797163771',
    projectId: 'guardians-notifications',
    storageBucket: 'guardians-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWZaT3ZGPOGcaiJYseGSpz9fkbXPPDPrE',
    appId: '1:11797163771:ios:379d95570fbb7f3bb6ca5e',
    messagingSenderId: '11797163771',
    projectId: 'guardians-notifications',
    storageBucket: 'guardians-notifications.firebasestorage.app',
    iosBundleId: 'com.ameyTech.guardiansApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWZaT3ZGPOGcaiJYseGSpz9fkbXPPDPrE',
    appId: '1:11797163771:ios:379d95570fbb7f3bb6ca5e',
    messagingSenderId: '11797163771',
    projectId: 'guardians-notifications',
    storageBucket: 'guardians-notifications.firebasestorage.app',
    iosBundleId: 'com.ameyTech.guardiansApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxXbfAmj4S98Ru0-XblorTuKHxzVJvRvs',
    appId: '1:11797163771:web:a0f212641ac2714ab6ca5e',
    messagingSenderId: '11797163771',
    projectId: 'guardians-notifications',
    authDomain: 'guardians-notifications.firebaseapp.com',
    storageBucket: 'guardians-notifications.firebasestorage.app',
  );
}
